### ISSUE TITLE
Fatal error :(

### ISSUE THREAD

**Issue by oarved** [MartinIngesen/HonnyPotter#1]
I run a wordpress 4.4 Installation on an apache2 server with php5.
If I try to activate this plugin, I get this error:
"Fatal error: Call to undefined function mcrypt_create_iv() in /var/www/html/wp-content/plugins/HonnyPotter/class.honnypotter.php on line 38"

**Comment by MartinIngesen** [comment]
My guess would be that you have to enable mcrypt in your PHP settings file. In the next version I will remove this dependency. A hotfix would be to go into the file class.honnypotter.php and change the line on 38 to "$random_log_file_name = "a-random-file name.log".
